name: zxbase_vault
description: Encrypted document store.
version: 3.0.4
homepage: https://zxbase.com
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  uuid: ^4.0.0
  zxbase_crypto:
    git: https://github.com/zxbase/zxbase_crypto

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
