name: zxbase_vault
description: Encrypted document store.
version: 3.0.1
homepage: https://zxbase.com
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  uuid: ^3.0.0
  zxbase_crypto:
    git: https://github.com/zxbase/zxbase_crypto

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
